# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
    'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

# Use the cocoapod CDN to speed up pod install
# https://blog.cocoapods.org/CocoaPods-1.7.2/
source 'https://cdn.cocoapods.org/'


platform :ios, 15.1
# use_modular_headers!
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => :static
end

# Disable use of AdId with analytics
# See #527 and
# https://rnfirebase.io/analytics/usage#disable-ad-id-usage-on-ios
# $RNFirebaseAnalyticsWithoutAdIdSupport=true
target 'mapswipe' do
  pod 'Firebase/AnalyticsWithoutAdIdSupport', '11.2.0', :modular_headers => true
  pod 'Firebase/Core', '11.2.0', :modular_headers => true
  pod 'Firebase/Auth', '11.2.0', :modular_headers => true

  config = use_native_modules!
  use_frameworks! :linkage => :static
  $RNFirebaseAsStaticFramework = true

  use_react_native!(
    :path => config[:reactNativePath],

    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )
  end
end
