# fastlane/Fastfile
default_platform :ios
setup_travis

platform :ios do
  before_all do
    cocoapods(repo_update: true)
  end

  desc "Runs all the tests"
  lane :test do
    scan(scheme: "mapswipe", configuration: "Debug", clean: true, devices:['iPhone X'], xcargs: "-quiet")
  end
end