# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(
      task: "clean assembleProductionRelease",
      print_command: false,
      properties: {
        "android.injected.signing.store.file" => ENV['PWD'] + "/app/mapswipe-production-release-key.keystore",
        "android.injected.signing.store.password" => ENV['MAPSWIPE_PRODUCTION_KEYSTORE_PASSWORD'],
        "android.injected.signing.key.alias" => ENV['MAPSWIPE_PRODUCTION_KEY_ALIAS'],
        "android.injected.signing.key.password" => ENV['MAPSWIPE_PRODUCTION_KEY_ALIAS_PASSWORD'],
      }
    )
    upload_to_play_store(track: 'internal', apk: 'app/build/outputs/apk/production/release/app-production-release.apk')
  end
end
