# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    # this step assumes that the build has already been done by a previous step in the CI process
    # via the `yarn buildProd` command
    upload_to_play_store(track: 'internal', apk: 'app/build/outputs/apk/production/release/app-production-release.apk')
    # Uploading an AAB requires opting-in to google managed signing keys, which in turn makes it much harder
    # to upload the same app to a different store. As we do not have to as of November 2021, we keep
    # using the APK upload, which means the github releases version and the playstore one are the same APK
    # upload_to_play_store(track: 'internal', aab: 'app/build/outputs/bundle/productionRelease/app-production-release.aab')
  end
end
